version: '3.8'
services:
    client:
        build: ./client
        ports:
            - 3000:3000
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - REACT_APP_API_ENV=dev
        command: yarn start

    server:
        build: ./server
        ports:
            - 5000:5000
        volumes:
            - ./server:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - REACT_APP_API_ENV=dev
        command: yarn serve

    zipkin:
        image: openzipkin/zipkin
        ports:
            - '9411:9411'
