version: '3.8'
services:
    client:
        build: ./client
        ports:
            - 3000:3000
        volumes:
            - ./client:/app
            - /app/client/node_modules
        environment:
            - NODE_ENV=development
            - REACT_APP_API_ENV=dev
            - DOCKER_ENV=true
        command: yarn start
        depends_on:
            - server

    server:
        build: ./server
        ports:
            - 5000:5000
            - 9464:9464 # prometheus
        volumes:
            - ./server:/app
            - /app/server/node_modules
        environment:
            - NODE_ENV=development
            - REACT_APP_API_ENV=dev
            - DOCKER_ENV=true
        command: yarn serve

    zipkin:
        image: openzipkin/zipkin
        ports:
            - '9411:9411'
        depends_on:
            - server

    prometheus:
        image: prom/prometheus
        volumes:
          - ./server/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 9090:9090
        depends_on:
            - server
